/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiOpenapiRouteImport } from './routes/api/openapi'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDescriptionRouteImport } from './routes/api/description'
import { Route as AppDataRouteImport } from './routes/_app/data'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppDeveloperRouteRouteImport } from './routes/_app/developer/route'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppModulesIndexRouteImport } from './routes/_app/modules/index'
import { Route as AppDeveloperIndexRouteImport } from './routes/_app/developer/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppToolsToolIdRouteImport } from './routes/_app/tools/$toolId'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppReportsReportIdRouteImport } from './routes/_app/reports/$reportId'
import { Route as AppModulesRecordIdRouteImport } from './routes/_app/modules/$recordId'
import { Route as AppDeveloperSdkRouteImport } from './routes/_app/developer/sdk'
import { Route as AppDeveloperModelRouteImport } from './routes/_app/developer/model'
import { Route as AppDeveloperMcpRouteImport } from './routes/_app/developer/mcp'
import { Route as AppDeveloperDesignSystemRouteImport } from './routes/_app/developer/design-system'
import { Route as AppDeveloperApiRouteImport } from './routes/_app/developer/api'
import { Route as AppSettingsModulesIndexRouteImport } from './routes/_app/settings/modules/index'
import { Route as AppSettingsCollectionIndexRouteImport } from './routes/_app/settings/$collection/index'
import { Route as AppObjectsObjectTypeIndexRouteImport } from './routes/_app/objects/$objectType/index'
import { Route as AppSettingsModulesRecordIdRouteImport } from './routes/_app/settings/modules/$recordId'
import { Route as AppSettingsCollectionRecordIdRouteImport } from './routes/_app/settings/$collection/$recordId'
import { Route as AppObjectsObjectTypeRecordIdRouteImport } from './routes/_app/objects/$objectType/$recordId'
import { Route as ApiV1AssetsAssetIdContentRouteImport } from './routes/api/v1/assets/$assetId/content'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiOpenapiRoute = ApiOpenapiRouteImport.update({
  id: '/api/openapi',
  path: '/api/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDescriptionRoute = ApiDescriptionRouteImport.update({
  id: '/api/description',
  path: '/api/description',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeveloperRouteRoute = AppDeveloperRouteRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModulesIndexRoute = AppModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeveloperIndexRoute = AppDeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsToolIdRoute = AppToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModulesRecordIdRoute = AppModulesRecordIdRouteImport.update({
  id: '/modules/$recordId',
  path: '/modules/$recordId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDeveloperSdkRoute = AppDeveloperSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperModelRoute = AppDeveloperModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperMcpRoute = AppDeveloperMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppDeveloperDesignSystemRoute =
  AppDeveloperDesignSystemRouteImport.update({
    id: '/design-system',
    path: '/design-system',
    getParentRoute: () => AppDeveloperRouteRoute,
  } as any)
const AppDeveloperApiRoute = AppDeveloperApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppDeveloperRouteRoute,
} as any)
const AppSettingsModulesIndexRoute = AppSettingsModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsCollectionIndexRoute =
  AppSettingsCollectionIndexRouteImport.update({
    id: '/$collection/',
    path: '/$collection/',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppObjectsObjectTypeIndexRoute =
  AppObjectsObjectTypeIndexRouteImport.update({
    id: '/objects/$objectType/',
    path: '/objects/$objectType/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsModulesRecordIdRoute =
  AppSettingsModulesRecordIdRouteImport.update({
    id: '/modules/$recordId',
    path: '/modules/$recordId',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsCollectionRecordIdRoute =
  AppSettingsCollectionRecordIdRouteImport.update({
    id: '/$collection/$recordId',
    path: '/$collection/$recordId',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppObjectsObjectTypeRecordIdRoute =
  AppObjectsObjectTypeRecordIdRouteImport.update({
    id: '/objects/$objectType/$recordId',
    path: '/objects/$objectType/$recordId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiV1AssetsAssetIdContentRoute =
  ApiV1AssetsAssetIdContentRouteImport.update({
    id: '/api/v1/assets/$assetId/content',
    path: '/api/v1/assets/$assetId/content',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/developer': typeof AppDeveloperRouteRouteWithChildren
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/data': typeof AppDataRoute
  '/api/description': typeof ApiDescriptionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/developer/api': typeof AppDeveloperApiRoute
  '/developer/design-system': typeof AppDeveloperDesignSystemRoute
  '/developer/mcp': typeof AppDeveloperMcpRoute
  '/developer/model': typeof AppDeveloperModelRoute
  '/developer/sdk': typeof AppDeveloperSdkRoute
  '/modules/$recordId': typeof AppModulesRecordIdRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/developer/': typeof AppDeveloperIndexRoute
  '/modules/': typeof AppModulesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/objects/$objectType/$recordId': typeof AppObjectsObjectTypeRecordIdRoute
  '/settings/$collection/$recordId': typeof AppSettingsCollectionRecordIdRoute
  '/settings/modules/$recordId': typeof AppSettingsModulesRecordIdRoute
  '/objects/$objectType/': typeof AppObjectsObjectTypeIndexRoute
  '/settings/$collection/': typeof AppSettingsCollectionIndexRoute
  '/settings/modules/': typeof AppSettingsModulesIndexRoute
  '/api/v1/assets/$assetId/content': typeof ApiV1AssetsAssetIdContentRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/data': typeof AppDataRoute
  '/api/description': typeof ApiDescriptionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/': typeof AppIndexRoute
  '/developer/api': typeof AppDeveloperApiRoute
  '/developer/design-system': typeof AppDeveloperDesignSystemRoute
  '/developer/mcp': typeof AppDeveloperMcpRoute
  '/developer/model': typeof AppDeveloperModelRoute
  '/developer/sdk': typeof AppDeveloperSdkRoute
  '/modules/$recordId': typeof AppModulesRecordIdRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/developer': typeof AppDeveloperIndexRoute
  '/modules': typeof AppModulesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/objects/$objectType/$recordId': typeof AppObjectsObjectTypeRecordIdRoute
  '/settings/$collection/$recordId': typeof AppSettingsCollectionRecordIdRoute
  '/settings/modules/$recordId': typeof AppSettingsModulesRecordIdRoute
  '/objects/$objectType': typeof AppObjectsObjectTypeIndexRoute
  '/settings/$collection': typeof AppSettingsCollectionIndexRoute
  '/settings/modules': typeof AppSettingsModulesIndexRoute
  '/api/v1/assets/$assetId/content': typeof ApiV1AssetsAssetIdContentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/_app/developer': typeof AppDeveloperRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/data': typeof AppDataRoute
  '/api/description': typeof ApiDescriptionRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/openapi': typeof ApiOpenapiRoute
  '/_app/': typeof AppIndexRoute
  '/_app/developer/api': typeof AppDeveloperApiRoute
  '/_app/developer/design-system': typeof AppDeveloperDesignSystemRoute
  '/_app/developer/mcp': typeof AppDeveloperMcpRoute
  '/_app/developer/model': typeof AppDeveloperModelRoute
  '/_app/developer/sdk': typeof AppDeveloperSdkRoute
  '/_app/modules/$recordId': typeof AppModulesRecordIdRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/tools/$toolId': typeof AppToolsToolIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/developer/': typeof AppDeveloperIndexRoute
  '/_app/modules/': typeof AppModulesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/objects/$objectType/$recordId': typeof AppObjectsObjectTypeRecordIdRoute
  '/_app/settings/$collection/$recordId': typeof AppSettingsCollectionRecordIdRoute
  '/_app/settings/modules/$recordId': typeof AppSettingsModulesRecordIdRoute
  '/_app/objects/$objectType/': typeof AppObjectsObjectTypeIndexRoute
  '/_app/settings/$collection/': typeof AppSettingsCollectionIndexRoute
  '/_app/settings/modules/': typeof AppSettingsModulesIndexRoute
  '/api/v1/assets/$assetId/content': typeof ApiV1AssetsAssetIdContentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/sign-in'
    | '/developer'
    | '/settings'
    | '/data'
    | '/api/description'
    | '/api/health'
    | '/api/mcp'
    | '/api/openapi'
    | '/developer/api'
    | '/developer/design-system'
    | '/developer/mcp'
    | '/developer/model'
    | '/developer/sdk'
    | '/modules/$recordId'
    | '/reports/$reportId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/tools/$toolId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/developer/'
    | '/modules/'
    | '/reports/'
    | '/settings/'
    | '/tools/'
    | '/objects/$objectType/$recordId'
    | '/settings/$collection/$recordId'
    | '/settings/modules/$recordId'
    | '/objects/$objectType/'
    | '/settings/$collection/'
    | '/settings/modules/'
    | '/api/v1/assets/$assetId/content'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/sign-in'
    | '/data'
    | '/api/description'
    | '/api/health'
    | '/api/mcp'
    | '/api/openapi'
    | '/'
    | '/developer/api'
    | '/developer/design-system'
    | '/developer/mcp'
    | '/developer/model'
    | '/developer/sdk'
    | '/modules/$recordId'
    | '/reports/$reportId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/tools/$toolId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/developer'
    | '/modules'
    | '/reports'
    | '/settings'
    | '/tools'
    | '/objects/$objectType/$recordId'
    | '/settings/$collection/$recordId'
    | '/settings/modules/$recordId'
    | '/objects/$objectType'
    | '/settings/$collection'
    | '/settings/modules'
    | '/api/v1/assets/$assetId/content'
  id:
    | '__root__'
    | '/_app'
    | '/health'
    | '/sign-in'
    | '/_app/developer'
    | '/_app/settings'
    | '/_app/data'
    | '/api/description'
    | '/api/health'
    | '/api/mcp'
    | '/api/openapi'
    | '/_app/'
    | '/_app/developer/api'
    | '/_app/developer/design-system'
    | '/_app/developer/mcp'
    | '/_app/developer/model'
    | '/_app/developer/sdk'
    | '/_app/modules/$recordId'
    | '/_app/reports/$reportId'
    | '/_app/settings/appearance'
    | '/_app/settings/profile'
    | '/_app/tools/$toolId'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/_app/developer/'
    | '/_app/modules/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/tools/'
    | '/_app/objects/$objectType/$recordId'
    | '/_app/settings/$collection/$recordId'
    | '/_app/settings/modules/$recordId'
    | '/_app/objects/$objectType/'
    | '/_app/settings/$collection/'
    | '/_app/settings/modules/'
    | '/api/v1/assets/$assetId/content'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  SignInRoute: typeof SignInRoute
  ApiDescriptionRoute: typeof ApiDescriptionRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOpenapiRoute: typeof ApiOpenapiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1AssetsAssetIdContentRoute: typeof ApiV1AssetsAssetIdContentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/openapi': {
      id: '/api/openapi'
      path: '/api/openapi'
      fullPath: '/api/openapi'
      preLoaderRoute: typeof ApiOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/description': {
      id: '/api/description'
      path: '/api/description'
      fullPath: '/api/description'
      preLoaderRoute: typeof ApiDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/modules/': {
      id: '/_app/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof AppModulesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/developer/': {
      id: '/_app/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof AppDeveloperIndexRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools/$toolId': {
      id: '/_app/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof AppToolsToolIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/modules/$recordId': {
      id: '/_app/modules/$recordId'
      path: '/modules/$recordId'
      fullPath: '/modules/$recordId'
      preLoaderRoute: typeof AppModulesRecordIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/developer/sdk': {
      id: '/_app/developer/sdk'
      path: '/sdk'
      fullPath: '/developer/sdk'
      preLoaderRoute: typeof AppDeveloperSdkRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/model': {
      id: '/_app/developer/model'
      path: '/model'
      fullPath: '/developer/model'
      preLoaderRoute: typeof AppDeveloperModelRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/mcp': {
      id: '/_app/developer/mcp'
      path: '/mcp'
      fullPath: '/developer/mcp'
      preLoaderRoute: typeof AppDeveloperMcpRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/design-system': {
      id: '/_app/developer/design-system'
      path: '/design-system'
      fullPath: '/developer/design-system'
      preLoaderRoute: typeof AppDeveloperDesignSystemRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/developer/api': {
      id: '/_app/developer/api'
      path: '/api'
      fullPath: '/developer/api'
      preLoaderRoute: typeof AppDeveloperApiRouteImport
      parentRoute: typeof AppDeveloperRouteRoute
    }
    '/_app/settings/modules/': {
      id: '/_app/settings/modules/'
      path: '/modules'
      fullPath: '/settings/modules/'
      preLoaderRoute: typeof AppSettingsModulesIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/$collection/': {
      id: '/_app/settings/$collection/'
      path: '/$collection'
      fullPath: '/settings/$collection/'
      preLoaderRoute: typeof AppSettingsCollectionIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/objects/$objectType/': {
      id: '/_app/objects/$objectType/'
      path: '/objects/$objectType'
      fullPath: '/objects/$objectType/'
      preLoaderRoute: typeof AppObjectsObjectTypeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/modules/$recordId': {
      id: '/_app/settings/modules/$recordId'
      path: '/modules/$recordId'
      fullPath: '/settings/modules/$recordId'
      preLoaderRoute: typeof AppSettingsModulesRecordIdRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/$collection/$recordId': {
      id: '/_app/settings/$collection/$recordId'
      path: '/$collection/$recordId'
      fullPath: '/settings/$collection/$recordId'
      preLoaderRoute: typeof AppSettingsCollectionRecordIdRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/objects/$objectType/$recordId': {
      id: '/_app/objects/$objectType/$recordId'
      path: '/objects/$objectType/$recordId'
      fullPath: '/objects/$objectType/$recordId'
      preLoaderRoute: typeof AppObjectsObjectTypeRecordIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/assets/$assetId/content': {
      id: '/api/v1/assets/$assetId/content'
      path: '/api/v1/assets/$assetId/content'
      fullPath: '/api/v1/assets/$assetId/content'
      preLoaderRoute: typeof ApiV1AssetsAssetIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDeveloperRouteRouteChildren {
  AppDeveloperApiRoute: typeof AppDeveloperApiRoute
  AppDeveloperDesignSystemRoute: typeof AppDeveloperDesignSystemRoute
  AppDeveloperMcpRoute: typeof AppDeveloperMcpRoute
  AppDeveloperModelRoute: typeof AppDeveloperModelRoute
  AppDeveloperSdkRoute: typeof AppDeveloperSdkRoute
  AppDeveloperIndexRoute: typeof AppDeveloperIndexRoute
}

const AppDeveloperRouteRouteChildren: AppDeveloperRouteRouteChildren = {
  AppDeveloperApiRoute: AppDeveloperApiRoute,
  AppDeveloperDesignSystemRoute: AppDeveloperDesignSystemRoute,
  AppDeveloperMcpRoute: AppDeveloperMcpRoute,
  AppDeveloperModelRoute: AppDeveloperModelRoute,
  AppDeveloperSdkRoute: AppDeveloperSdkRoute,
  AppDeveloperIndexRoute: AppDeveloperIndexRoute,
}

const AppDeveloperRouteRouteWithChildren =
  AppDeveloperRouteRoute._addFileChildren(AppDeveloperRouteRouteChildren)

interface AppSettingsRouteRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsCollectionRecordIdRoute: typeof AppSettingsCollectionRecordIdRoute
  AppSettingsModulesRecordIdRoute: typeof AppSettingsModulesRecordIdRoute
  AppSettingsCollectionIndexRoute: typeof AppSettingsCollectionIndexRoute
  AppSettingsModulesIndexRoute: typeof AppSettingsModulesIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsCollectionRecordIdRoute: AppSettingsCollectionRecordIdRoute,
  AppSettingsModulesRecordIdRoute: AppSettingsModulesRecordIdRoute,
  AppSettingsCollectionIndexRoute: AppSettingsCollectionIndexRoute,
  AppSettingsModulesIndexRoute: AppSettingsModulesIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppDeveloperRouteRoute: typeof AppDeveloperRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppDataRoute: typeof AppDataRoute
  AppIndexRoute: typeof AppIndexRoute
  AppModulesRecordIdRoute: typeof AppModulesRecordIdRoute
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppToolsToolIdRoute: typeof AppToolsToolIdRoute
  AppModulesIndexRoute: typeof AppModulesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppObjectsObjectTypeRecordIdRoute: typeof AppObjectsObjectTypeRecordIdRoute
  AppObjectsObjectTypeIndexRoute: typeof AppObjectsObjectTypeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDeveloperRouteRoute: AppDeveloperRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppDataRoute: AppDataRoute,
  AppIndexRoute: AppIndexRoute,
  AppModulesRecordIdRoute: AppModulesRecordIdRoute,
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppToolsToolIdRoute: AppToolsToolIdRoute,
  AppModulesIndexRoute: AppModulesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppObjectsObjectTypeRecordIdRoute: AppObjectsObjectTypeRecordIdRoute,
  AppObjectsObjectTypeIndexRoute: AppObjectsObjectTypeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  SignInRoute: SignInRoute,
  ApiDescriptionRoute: ApiDescriptionRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOpenapiRoute: ApiOpenapiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1AssetsAssetIdContentRoute: ApiV1AssetsAssetIdContentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
